[2024-03-05 23:07:27,058] 96 werkzeug -WARNING  * Debugger is active!
[2024-03-05 23:07:27,070] 96 werkzeug -INFO  * Debugger PIN: 274-803-487
[2024-03-05 23:07:27,705] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:27] "[35m[1mPOST / HTTP/1.1[0m" 500 -
[2024-03-05 23:07:27,712] 96 werkzeug -ERROR Error on request:
Traceback (most recent call last):
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\debug\__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\flask-3.0.2-py3.8.egg\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\app.py", line 107, in predict_datapoint
    shoulder=int(final_measurements[0]*100),
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\serving.py", line 325, in execute
    for data in application_iter:
  File "D:\DevOps\Project\BE Project\Outfit Recommendation\env\lib\site-packages\werkzeug\debug\__init__.py", line 365, in debug_application
    environ["wsgi.errors"].write("".join(tb.render_traceback_text()))
OSError: [WinError 6] The handle is invalid
[2024-03-05 23:07:27,732] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:27] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
[2024-03-05 23:07:27,738] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:27] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
[2024-03-05 23:07:27,764] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:27] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
[2024-03-05 23:07:27,812] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:27] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
[2024-03-05 23:07:35,180] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:35] "GET / HTTP/1.1" 200 -
[2024-03-05 23:07:35,846] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:35] "GET /video HTTP/1.1" 200 -
[2024-03-05 23:07:47,004] 73 root -INFO Data Frame Gathered
[2024-03-05 23:07:47,229] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:47] "POST / HTTP/1.1" 200 -
[2024-03-05 23:07:47,248] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:47] "[36mGET /static/vshapemen/1.jpeg HTTP/1.1[0m" 304 -
[2024-03-05 23:07:47,255] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:47] "[36mGET /static/vshapemen/2.jpg HTTP/1.1[0m" 304 -
[2024-03-05 23:07:47,258] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:47] "[36mGET /static/vshapemen/3.jpeg HTTP/1.1[0m" 304 -
[2024-03-05 23:07:47,262] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:47] "[36mGET /static/vshapemen/4.jpg HTTP/1.1[0m" 304 -
[2024-03-05 23:07:49,220] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:49] "GET / HTTP/1.1" 200 -
[2024-03-05 23:07:53,967] 73 root -INFO Data Frame Gathered
[2024-03-05 23:07:54,060] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:54] "POST / HTTP/1.1" 200 -
[2024-03-05 23:07:54,086] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:54] "[36mGET /static/Hourglass/1.png HTTP/1.1[0m" 304 -
[2024-03-05 23:07:54,095] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:54] "[36mGET /static/Hourglass/2.jpg HTTP/1.1[0m" 304 -
[2024-03-05 23:07:54,100] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:54] "[36mGET /static/Hourglass/3.jpg HTTP/1.1[0m" 304 -
[2024-03-05 23:07:54,104] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:54] "[36mGET /static/Hourglass/4.jpeg HTTP/1.1[0m" 304 -
[2024-03-05 23:07:55,889] 96 werkzeug -INFO 127.0.0.1 - - [05/Mar/2024 23:07:55] "GET / HTTP/1.1" 200 -
[2024-03-05 23:12:50,789] 96 werkzeug -INFO  * Detected change in 'd:\\devops\\project\\be project\\outfit recommendation\\app.py', reloading
